### ISSUE TITLE
[Feature Request] shpec

### ISSUE THREAD

**Issue by schorsch3000** [dodie/testing-in-bash#2]
Hi,
im using [shpec](https://github.com/rylnd/shpec) for my bash-testing-purpose.
Would you be willing to either add that to your by your own or have me do that and accept a PR?

Thanks, schorsch

**Comment by dodie** [comment]
Hi @schorsch3000 ,

Wow, I completely missed shspec, thanks for letting me know. I think it would definitely have its place in this comparison.  👍 

I can also give it a try, but since you have more knowledge about it, I'd be glad if you could provide your experiences with this tool and could add it to the comparison.

Thanks,
David

**Comment by schorsch3000** [comment]
i hat to look twice if shpec and shellspec aren't the same :)

I'm unsure if using just my part might be good,  since i'm not super familiar with the other tools, but for sure i can do a shpec-part and led you do the conclusion. But before i'll do that we should ask @rylnd if he would linkes to do so :)

**Comment by dodie** [comment]
Yes, shpec and shellspec indeed looks quite similar. I'd be interested in the differences.

> for sure i can do a shpec-part and led you do the conclusion

I think this can work. Feel free to open a PR with your experiences, and I'll also give shpec a test-drive! 😄

**Comment by schorsch3000** [comment]
I'll read and try out the other examples and will make a shpec example along the lines.
I will to it this weekend (if plans went well, at least there is a appointment in my calender :) )

**Comment by schorsch3000** [comment]
Hey, see #3  :)

**Comment by dodie** [comment]
I've merged the PR and added it to the landing page🚀
The comparison table is not yet complete with all the attributes, I plan to fill it as I have the time.
