### ISSUE TITLE
Add bashunit

### ISSUE THREAD

**Issue by CosmeValera** [dodie/testing-in-bash#9]
There's a new library that has gotten over 50 stars ⭐ in its GiHub repository in its first week:
- Click [here](https://github.com/TypedDevs/bashunit) to see the bashunit repository. 

Its aim is to create a simple testing library for bash scripts, and I think it would make a good fit for this repository, so people could compare it with the others when making their choice. 🐱

**Comment by dodie** [comment]
Hi @CosmeValera,

Thanks, looks interesting indeed! Would you be up to add an example project to this repository (with similar structure to existing `example-<setlib>` projects - please see the [contribution guide](https://github.com/dodie/testing-in-bash/blob/master/CONTRIBUTING.md)) to demonstrate its capabilities?

Thanks and cheers,
Dávid

**Comment by Chemaclass** [comment]
I will take over preparing an example for this repo. It might take a few days, because I want to focus first on fixing a couple features and one bug we recently discover, aka: in a couple of days, we would be able to create a new release, and then I will take care of this. Thanks for finding this, @CosmeValera ! And thanks @dodie for the great repo-comparison here! 😄  CC: @khru @tito-kati

**Comment by dodie** [comment]
Thanks, I'm looking forward to it @Chemaclass

**Comment by CosmeValera** [comment]
I think this is done now :)

https://github.com/dodie/testing-in-bash/pull/10#issuecomment-2030418236

**Comment by CosmeValera** [comment]
Anyway maybe it would be beneficial to add the bashunit library for the comparison in the `readme.md`.

Maybe we should wait for that to be done before closing this issue. What are your thoughts? 🤔

**Comment by dodie** [comment]
Hi @CosmeValera ,
My thoughts exactly. I think adding bashunit to the main readme file would make sense to make it more visible/comparable with the others. I hope to find some time to test bashunit in the near future and write it - unless somebody from the community picks this topic up faster.
Cheers,
Dávid
